#############################################################################
# Makefile for building: batch_acquisition_system
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  batch_acquisition_system.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile batch_acquisition_system.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -IUI -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = batch_acquisition_system1.0.0
DISTDIR = /home/wenyun/桌面/QT/batch_acquisition_system/.tmp/batch_acquisition_system1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		login.cpp \
		registered.cpp \
		getpasswd.cpp \
		mainwindow.cpp \
		changepasswd.cpp \
		authentication.cpp \
		registrationinfo.cpp \
		getlog.cpp \
		viewbatch.cpp \
		setpermissions.cpp \
		viewproline.cpp \
		setproline.cpp \
		modifyproline.cpp \
		currentperson.cpp \
		serverservice.cpp \
		dbhelper.cpp \
		qres.cpp \
		quser.cpp \
		utils.cpp \
		product.cpp \
		qbatch.cpp \
		saveproduct.cpp \
		loger.cpp \
		maintaindata.cpp \
		viewdata.cpp \
		addbatch.cpp \
		filedata.cpp \
		qtray.cpp \
		qpnglineedit.cpp \
		userinfo.cpp \
		changepermision.cpp \
		test.cpp \
		mainwds.cpp \
		mainwdsforonepage.cpp \
		mainwdsfortwopage.cpp \
		mainwdsforthreepage.cpp \
		mainwdsforfivepage.cpp \
		mainwdsforfourpage.cpp \
		iconhelper.cpp \
		frmmessagebox.cpp \
		frmmain.cpp \
		mainwindowsforall.cpp \
		work.cpp qrc_icons.cpp \
		qrc_rc.cpp \
		moc_login.cpp \
		moc_registered.cpp \
		moc_getpasswd.cpp \
		moc_mainwindow.cpp \
		moc_changepasswd.cpp \
		moc_authentication.cpp \
		moc_registrationinfo.cpp \
		moc_getlog.cpp \
		moc_viewbatch.cpp \
		moc_setpermissions.cpp \
		moc_viewproline.cpp \
		moc_setproline.cpp \
		moc_modifyproline.cpp \
		moc_saveproduct.cpp \
		moc_maintaindata.cpp \
		moc_viewdata.cpp \
		moc_addbatch.cpp \
		moc_qpnglineedit.cpp \
		moc_changepermision.cpp \
		moc_test.cpp \
		moc_mainwds.cpp \
		moc_mainwdsforonepage.cpp \
		moc_mainwdsfortwopage.cpp \
		moc_mainwdsforthreepage.cpp \
		moc_mainwdsforfivepage.cpp \
		moc_mainwdsforfourpage.cpp \
		moc_frmmessagebox.cpp \
		moc_frmmain.cpp \
		moc_mainwindowsforall.cpp \
		moc_work.cpp
OBJECTS       = main.o \
		login.o \
		registered.o \
		getpasswd.o \
		mainwindow.o \
		changepasswd.o \
		authentication.o \
		registrationinfo.o \
		getlog.o \
		viewbatch.o \
		setpermissions.o \
		viewproline.o \
		setproline.o \
		modifyproline.o \
		currentperson.o \
		serverservice.o \
		dbhelper.o \
		qres.o \
		quser.o \
		utils.o \
		product.o \
		qbatch.o \
		saveproduct.o \
		loger.o \
		maintaindata.o \
		viewdata.o \
		addbatch.o \
		filedata.o \
		qtray.o \
		qpnglineedit.o \
		userinfo.o \
		changepermision.o \
		test.o \
		mainwds.o \
		mainwdsforonepage.o \
		mainwdsfortwopage.o \
		mainwdsforthreepage.o \
		mainwdsforfivepage.o \
		mainwdsforfourpage.o \
		iconhelper.o \
		frmmessagebox.o \
		frmmain.o \
		mainwindowsforall.o \
		work.o \
		qrc_icons.o \
		qrc_rc.o \
		moc_login.o \
		moc_registered.o \
		moc_getpasswd.o \
		moc_mainwindow.o \
		moc_changepasswd.o \
		moc_authentication.o \
		moc_registrationinfo.o \
		moc_getlog.o \
		moc_viewbatch.o \
		moc_setpermissions.o \
		moc_viewproline.o \
		moc_setproline.o \
		moc_modifyproline.o \
		moc_saveproduct.o \
		moc_maintaindata.o \
		moc_viewdata.o \
		moc_addbatch.o \
		moc_qpnglineedit.o \
		moc_changepermision.o \
		moc_test.o \
		moc_mainwds.o \
		moc_mainwdsforonepage.o \
		moc_mainwdsfortwopage.o \
		moc_mainwdsforthreepage.o \
		moc_mainwdsforfivepage.o \
		moc_mainwdsforfourpage.o \
		moc_frmmessagebox.o \
		moc_frmmain.o \
		moc_mainwindowsforall.o \
		moc_work.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		batch_acquisition_system.pro login.h \
		registered.h \
		getpasswd.h \
		mainwindow.h \
		changepasswd.h \
		authentication.h \
		registrationinfo.h \
		getlog.h \
		viewbatch.h \
		setpermissions.h \
		viewproline.h \
		setproline.h \
		modifyproline.h \
		session.h \
		serverservice.h \
		dbhelper.h \
		qres.h \
		quser.h \
		utils.h \
		product.h \
		qbatch.h \
		qtray.h \
		saveproduct.h \
		loger.h \
		maintaindata.h \
		viewdata.h \
		addbatch.h \
		filedata.h \
		qpnglineedit.h \
		userinfo.h \
		changepermision.h \
		test.h \
		mainwds.h \
		mainwdsforonepage.h \
		mainwdsfortwopage.h \
		mainwdsforthreepage.h \
		mainwdsforfivepage.h \
		mainwdsforfourpage.h \
		iconhelper.h \
		myhelper.h \
		frmmessagebox.h \
		frmmain.h \
		mainwindowsforall.h \
		work.h main.cpp \
		login.cpp \
		registered.cpp \
		getpasswd.cpp \
		mainwindow.cpp \
		changepasswd.cpp \
		authentication.cpp \
		registrationinfo.cpp \
		getlog.cpp \
		viewbatch.cpp \
		setpermissions.cpp \
		viewproline.cpp \
		setproline.cpp \
		modifyproline.cpp \
		currentperson.cpp \
		serverservice.cpp \
		dbhelper.cpp \
		qres.cpp \
		quser.cpp \
		utils.cpp \
		product.cpp \
		qbatch.cpp \
		saveproduct.cpp \
		loger.cpp \
		maintaindata.cpp \
		viewdata.cpp \
		addbatch.cpp \
		filedata.cpp \
		qtray.cpp \
		qpnglineedit.cpp \
		userinfo.cpp \
		changepermision.cpp \
		test.cpp \
		mainwds.cpp \
		mainwdsforonepage.cpp \
		mainwdsfortwopage.cpp \
		mainwdsforthreepage.cpp \
		mainwdsforfivepage.cpp \
		mainwdsforfourpage.cpp \
		iconhelper.cpp \
		frmmessagebox.cpp \
		frmmain.cpp \
		mainwindowsforall.cpp \
		work.cpp
QMAKE_TARGET  = batch_acquisition_system
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = batch_acquisition_system


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): UI/ui_login.h UI/ui_registered.h UI/ui_getpasswd.h UI/ui_mainwindow.h UI/ui_changepasswd.h UI/ui_authentication.h UI/ui_registrationinfo.h UI/ui_getlog.h UI/ui_viewbatch.h UI/ui_setpermissions.h UI/ui_viewproline.h UI/ui_setproline.h UI/ui_modifyproline.h UI/ui_saveproduct.h UI/ui_maintaindata.h UI/ui_viewdata.h UI/ui_addbatch.h UI/ui_changepermision.h UI/ui_test.h UI/ui_mainwds.h UI/ui_mainwdsforonepage.h UI/ui_mainwdsfortwopage.h UI/ui_mainwdsforthreepage.h UI/ui_mainwdsforfivepage.h UI/ui_mainwdsforfourpage.h UI/ui_frmmessagebox.h UI/ui_frmmain.h UI/ui_mainwindowsforall.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: batch_acquisition_system.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		batch_acquisition_system.pro \
		icons.qrc \
		rc.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile batch_acquisition_system.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
batch_acquisition_system.pro:
icons.qrc:
rc.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile batch_acquisition_system.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc rc.qrc $(DISTDIR)/
	$(COPY_FILE) --parents login.h registered.h getpasswd.h mainwindow.h changepasswd.h authentication.h registrationinfo.h getlog.h viewbatch.h setpermissions.h viewproline.h setproline.h modifyproline.h session.h serverservice.h dbhelper.h qres.h quser.h utils.h product.h qbatch.h qtray.h saveproduct.h loger.h maintaindata.h viewdata.h addbatch.h filedata.h qpnglineedit.h userinfo.h changepermision.h test.h mainwds.h mainwdsforonepage.h mainwdsfortwopage.h mainwdsforthreepage.h mainwdsforfivepage.h mainwdsforfourpage.h iconhelper.h myhelper.h frmmessagebox.h frmmain.h mainwindowsforall.h work.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp login.cpp registered.cpp getpasswd.cpp mainwindow.cpp changepasswd.cpp authentication.cpp registrationinfo.cpp getlog.cpp viewbatch.cpp setpermissions.cpp viewproline.cpp setproline.cpp modifyproline.cpp currentperson.cpp serverservice.cpp dbhelper.cpp qres.cpp quser.cpp utils.cpp product.cpp qbatch.cpp saveproduct.cpp loger.cpp maintaindata.cpp viewdata.cpp addbatch.cpp filedata.cpp qtray.cpp qpnglineedit.cpp userinfo.cpp changepermision.cpp test.cpp mainwds.cpp mainwdsforonepage.cpp mainwdsfortwopage.cpp mainwdsforthreepage.cpp mainwdsforfivepage.cpp mainwdsforfourpage.cpp iconhelper.cpp frmmessagebox.cpp frmmain.cpp mainwindowsforall.cpp work.cpp $(DISTDIR)/
	$(COPY_FILE) --parents login.ui registered.ui getpasswd.ui mainwindow.ui changepasswd.ui authentication.ui registrationinfo.ui getlog.ui viewbatch.ui setpermissions.ui viewproline.ui setproline.ui modifyproline.ui saveproduct.ui maintaindata.ui viewdata.ui addbatch.ui changepermision.ui test.ui mainwds.ui mainwdsforonepage.ui mainwdsfortwopage.ui mainwdsforthreepage.ui mainwdsforfivepage.ui mainwdsforfourpage.ui frmmessagebox.ui frmmain.ui mainwindowsforall.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_icons.cpp qrc_rc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_rc.cpp
qrc_icons.cpp: icons.qrc \
		images/woman.jpg \
		images/2.png \
		images/name.jpg \
		images/userid.png \
		images/1.png \
		images/5.png \
		images/11.jpg \
		images/level.jpg \
		images/newKey.jpg \
		images/4.png \
		images/age.jpg \
		images/man.jpg \
		images/key.png \
		images/job.jpg \
		images/3.png \
		images/oldKey.jpg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

qrc_rc.cpp: rc.qrc \
		image/blue.css \
		image/gray.css \
		image/radio_normal.png \
		image/fontawesome-webfont.ttf \
		image/sub-line_vertical.png \
		image/checkbox_checked.png \
		image/black.css \
		image/array_down.png \
		image/info.png \
		image/add-line_vertical.png \
		image/checkbox_unchecked.png \
		image/radio_selected.png \
		image/sub-line_horizontal.png \
		image/error.png \
		image/navy.css \
		image/add-line_horizontal.png \
		image/question.png \
		image/qt_zh_CN.qm
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name rc rc.qrc -o qrc_rc.cpp

compiler_moc_header_make_all: moc_login.cpp moc_registered.cpp moc_getpasswd.cpp moc_mainwindow.cpp moc_changepasswd.cpp moc_authentication.cpp moc_registrationinfo.cpp moc_getlog.cpp moc_viewbatch.cpp moc_setpermissions.cpp moc_viewproline.cpp moc_setproline.cpp moc_modifyproline.cpp moc_saveproduct.cpp moc_maintaindata.cpp moc_viewdata.cpp moc_addbatch.cpp moc_qpnglineedit.cpp moc_changepermision.cpp moc_test.cpp moc_mainwds.cpp moc_mainwdsforonepage.cpp moc_mainwdsfortwopage.cpp moc_mainwdsforthreepage.cpp moc_mainwdsforfivepage.cpp moc_mainwdsforfourpage.cpp moc_frmmessagebox.cpp moc_frmmain.cpp moc_mainwindowsforall.cpp moc_work.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_login.cpp moc_registered.cpp moc_getpasswd.cpp moc_mainwindow.cpp moc_changepasswd.cpp moc_authentication.cpp moc_registrationinfo.cpp moc_getlog.cpp moc_viewbatch.cpp moc_setpermissions.cpp moc_viewproline.cpp moc_setproline.cpp moc_modifyproline.cpp moc_saveproduct.cpp moc_maintaindata.cpp moc_viewdata.cpp moc_addbatch.cpp moc_qpnglineedit.cpp moc_changepermision.cpp moc_test.cpp moc_mainwds.cpp moc_mainwdsforonepage.cpp moc_mainwdsfortwopage.cpp moc_mainwdsforthreepage.cpp moc_mainwdsforfivepage.cpp moc_mainwdsforfourpage.cpp moc_frmmessagebox.cpp moc_frmmain.cpp moc_mainwindowsforall.cpp moc_work.cpp
moc_login.cpp: login.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include login.h -o moc_login.cpp

moc_registered.cpp: login.h \
		registered.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include registered.h -o moc_registered.cpp

moc_getpasswd.cpp: getpasswd.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include getpasswd.h -o moc_getpasswd.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_changepasswd.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		changepasswd.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include changepasswd.h -o moc_changepasswd.cpp

moc_authentication.cpp: authentication.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include authentication.h -o moc_authentication.cpp

moc_registrationinfo.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		registrationinfo.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include registrationinfo.h -o moc_registrationinfo.cpp

moc_getlog.cpp: getlog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include getlog.h -o moc_getlog.cpp

moc_viewbatch.cpp: qbatch.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		userinfo.h \
		viewbatch.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewbatch.h -o moc_viewbatch.cpp

moc_setpermissions.cpp: changepermision.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		setpermissions.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include setpermissions.h -o moc_setpermissions.cpp

moc_viewproline.cpp: viewproline.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewproline.h -o moc_viewproline.cpp

moc_setproline.cpp: setproline.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include setproline.h -o moc_setproline.cpp

moc_modifyproline.cpp: modifyproline.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include modifyproline.h -o moc_modifyproline.cpp

moc_saveproduct.cpp: product.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		session.h \
		saveproduct.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include saveproduct.h -o moc_saveproduct.cpp

moc_maintaindata.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		saveproduct.h \
		session.h \
		maintaindata.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include maintaindata.h -o moc_maintaindata.cpp

moc_viewdata.cpp: filedata.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		qbatch.h \
		userinfo.h \
		viewdata.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewdata.h -o moc_viewdata.cpp

moc_addbatch.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		addbatch.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include addbatch.h -o moc_addbatch.cpp

moc_qpnglineedit.cpp: qpnglineedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include qpnglineedit.h -o moc_qpnglineedit.cpp

moc_changepermision.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		changepermision.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include changepermision.h -o moc_changepermision.cpp

moc_test.cpp: test.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include test.h -o moc_test.cpp

moc_mainwds.cpp: mainwds.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwds.h -o moc_mainwds.cpp

moc_mainwdsforonepage.cpp: mainwdsforonepage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwdsforonepage.h -o moc_mainwdsforonepage.cpp

moc_mainwdsfortwopage.cpp: mainwdsfortwopage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwdsfortwopage.h -o moc_mainwdsfortwopage.cpp

moc_mainwdsforthreepage.cpp: mainwdsforthreepage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwdsforthreepage.h -o moc_mainwdsforthreepage.cpp

moc_mainwdsforfivepage.cpp: mainwdsforfivepage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwdsforfivepage.h -o moc_mainwdsforfivepage.cpp

moc_mainwdsforfourpage.cpp: mainwdsforfourpage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwdsforfourpage.h -o moc_mainwdsforfourpage.cpp

moc_frmmessagebox.cpp: frmmessagebox.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include frmmessagebox.h -o moc_frmmessagebox.cpp

moc_frmmain.cpp: frmmain.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include frmmain.h -o moc_frmmain.cpp

moc_mainwindowsforall.cpp: mainwindowsforall.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindowsforall.h -o moc_mainwindowsforall.cpp

moc_work.cpp: dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		work.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/wenyun/桌面/QT/batch_acquisition_system -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include work.h -o moc_work.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: UI/ui_login.h UI/ui_registered.h UI/ui_getpasswd.h UI/ui_mainwindow.h UI/ui_changepasswd.h UI/ui_authentication.h UI/ui_registrationinfo.h UI/ui_getlog.h UI/ui_viewbatch.h UI/ui_setpermissions.h UI/ui_viewproline.h UI/ui_setproline.h UI/ui_modifyproline.h UI/ui_saveproduct.h UI/ui_maintaindata.h UI/ui_viewdata.h UI/ui_addbatch.h UI/ui_changepermision.h UI/ui_test.h UI/ui_mainwds.h UI/ui_mainwdsforonepage.h UI/ui_mainwdsfortwopage.h UI/ui_mainwdsforthreepage.h UI/ui_mainwdsforfivepage.h UI/ui_mainwdsforfourpage.h UI/ui_frmmessagebox.h UI/ui_frmmain.h UI/ui_mainwindowsforall.h
compiler_uic_clean:
	-$(DEL_FILE) UI/ui_login.h UI/ui_registered.h UI/ui_getpasswd.h UI/ui_mainwindow.h UI/ui_changepasswd.h UI/ui_authentication.h UI/ui_registrationinfo.h UI/ui_getlog.h UI/ui_viewbatch.h UI/ui_setpermissions.h UI/ui_viewproline.h UI/ui_setproline.h UI/ui_modifyproline.h UI/ui_saveproduct.h UI/ui_maintaindata.h UI/ui_viewdata.h UI/ui_addbatch.h UI/ui_changepermision.h UI/ui_test.h UI/ui_mainwds.h UI/ui_mainwdsforonepage.h UI/ui_mainwdsfortwopage.h UI/ui_mainwdsforthreepage.h UI/ui_mainwdsforfivepage.h UI/ui_mainwdsforfourpage.h UI/ui_frmmessagebox.h UI/ui_frmmain.h UI/ui_mainwindowsforall.h
UI/ui_login.h: login.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic login.ui -o UI/ui_login.h

UI/ui_registered.h: registered.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic registered.ui -o UI/ui_registered.h

UI/ui_getpasswd.h: getpasswd.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic getpasswd.ui -o UI/ui_getpasswd.h

UI/ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o UI/ui_mainwindow.h

UI/ui_changepasswd.h: changepasswd.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic changepasswd.ui -o UI/ui_changepasswd.h

UI/ui_authentication.h: authentication.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic authentication.ui -o UI/ui_authentication.h

UI/ui_registrationinfo.h: registrationinfo.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic registrationinfo.ui -o UI/ui_registrationinfo.h

UI/ui_getlog.h: getlog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic getlog.ui -o UI/ui_getlog.h

UI/ui_viewbatch.h: viewbatch.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic viewbatch.ui -o UI/ui_viewbatch.h

UI/ui_setpermissions.h: setpermissions.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic setpermissions.ui -o UI/ui_setpermissions.h

UI/ui_viewproline.h: viewproline.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic viewproline.ui -o UI/ui_viewproline.h

UI/ui_setproline.h: setproline.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic setproline.ui -o UI/ui_setproline.h

UI/ui_modifyproline.h: modifyproline.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic modifyproline.ui -o UI/ui_modifyproline.h

UI/ui_saveproduct.h: saveproduct.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic saveproduct.ui -o UI/ui_saveproduct.h

UI/ui_maintaindata.h: maintaindata.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic maintaindata.ui -o UI/ui_maintaindata.h

UI/ui_viewdata.h: viewdata.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic viewdata.ui -o UI/ui_viewdata.h

UI/ui_addbatch.h: addbatch.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic addbatch.ui -o UI/ui_addbatch.h

UI/ui_changepermision.h: changepermision.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic changepermision.ui -o UI/ui_changepermision.h

UI/ui_test.h: test.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic test.ui -o UI/ui_test.h

UI/ui_mainwds.h: mainwds.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwds.ui -o UI/ui_mainwds.h

UI/ui_mainwdsforonepage.h: mainwdsforonepage.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwdsforonepage.ui -o UI/ui_mainwdsforonepage.h

UI/ui_mainwdsfortwopage.h: mainwdsfortwopage.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwdsfortwopage.ui -o UI/ui_mainwdsfortwopage.h

UI/ui_mainwdsforthreepage.h: mainwdsforthreepage.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwdsforthreepage.ui -o UI/ui_mainwdsforthreepage.h

UI/ui_mainwdsforfivepage.h: mainwdsforfivepage.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwdsforfivepage.ui -o UI/ui_mainwdsforfivepage.h

UI/ui_mainwdsforfourpage.h: mainwdsforfourpage.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwdsforfourpage.ui -o UI/ui_mainwdsforfourpage.h

UI/ui_frmmessagebox.h: frmmessagebox.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmmessagebox.ui -o UI/ui_frmmessagebox.h

UI/ui_frmmain.h: frmmain.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic frmmain.ui -o UI/ui_frmmain.h

UI/ui_mainwindowsforall.h: mainwindowsforall.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindowsforall.ui -o UI/ui_mainwindowsforall.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp login.h \
		mainwindow.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		mainwds.h \
		mainwdsforonepage.h \
		myhelper.h \
		frmmessagebox.h \
		viewdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

login.o: login.cpp login.h \
		UI/ui_login.h \
		registered.h \
		getpasswd.h \
		mainwindow.h \
		session.h \
		utils.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		qpnglineedit.h \
		mainwds.h \
		mainwindowsforall.h \
		staticdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

registered.o: registered.cpp registered.h \
		login.h \
		UI/ui_registered.h \
		quser.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		qpnglineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registered.o registered.cpp

getpasswd.o: getpasswd.cpp getpasswd.h \
		login.h \
		UI/ui_getpasswd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getpasswd.o getpasswd.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		UI/ui_mainwindow.h \
		login.h \
		authentication.h \
		registrationinfo.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		changepasswd.h \
		getlog.h \
		viewbatch.h \
		maintaindata.h \
		saveproduct.h \
		session.h \
		viewdata.h \
		setpermissions.h \
		changepermision.h \
		viewproline.h \
		setproline.h \
		modifyproline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

changepasswd.o: changepasswd.cpp changepasswd.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		UI/ui_changepasswd.h \
		session.h \
		utils.h \
		qpnglineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changepasswd.o changepasswd.cpp

authentication.o: authentication.cpp authentication.h \
		UI/ui_authentication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authentication.o authentication.cpp

registrationinfo.o: registrationinfo.cpp registrationinfo.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		UI/ui_registrationinfo.h \
		session.h \
		qpnglineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registrationinfo.o registrationinfo.cpp

getlog.o: getlog.cpp getlog.h \
		UI/ui_getlog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getlog.o getlog.cpp

viewbatch.o: viewbatch.cpp viewbatch.h \
		qbatch.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		userinfo.h \
		UI/ui_viewbatch.h \
		addbatch.h \
		viewdatathread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewbatch.o viewbatch.cpp

setpermissions.o: setpermissions.cpp setpermissions.h \
		changepermision.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		UI/ui_setpermissions.h \
		session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setpermissions.o setpermissions.cpp

viewproline.o: viewproline.cpp viewproline.h \
		UI/ui_viewproline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewproline.o viewproline.cpp

setproline.o: setproline.cpp setproline.h \
		UI/ui_setproline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setproline.o setproline.cpp

modifyproline.o: modifyproline.cpp modifyproline.h \
		UI/ui_modifyproline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifyproline.o modifyproline.cpp

currentperson.o: currentperson.cpp session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o currentperson.o currentperson.cpp

serverservice.o: serverservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverservice.o serverservice.cpp

dbhelper.o: dbhelper.cpp dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		loger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbhelper.o dbhelper.cpp

qres.o: qres.cpp qres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qres.o qres.cpp

quser.o: quser.cpp quser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quser.o quser.cpp

utils.o: utils.cpp utils.h \
		session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

product.o: product.cpp product.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product.o product.cpp

qbatch.o: qbatch.cpp qbatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbatch.o qbatch.cpp

saveproduct.o: saveproduct.cpp saveproduct.h \
		product.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		session.h \
		UI/ui_saveproduct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveproduct.o saveproduct.cpp

loger.o: loger.cpp loger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loger.o loger.cpp

maintaindata.o: maintaindata.cpp maintaindata.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		saveproduct.h \
		session.h \
		UI/ui_maintaindata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maintaindata.o maintaindata.cpp

viewdata.o: viewdata.cpp viewdata.h \
		filedata.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		qbatch.h \
		userinfo.h \
		UI/ui_viewdata.h \
		session.h \
		work.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewdata.o viewdata.cpp

addbatch.o: addbatch.cpp addbatch.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		UI/ui_addbatch.h \
		session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addbatch.o addbatch.cpp

filedata.o: filedata.cpp filedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedata.o filedata.cpp

qtray.o: qtray.cpp qtray.h \
		product.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtray.o qtray.cpp

qpnglineedit.o: qpnglineedit.cpp qpnglineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpnglineedit.o qpnglineedit.cpp

userinfo.o: userinfo.cpp userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinfo.o userinfo.cpp

changepermision.o: changepermision.cpp changepermision.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		UI/ui_changepermision.h \
		session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changepermision.o changepermision.cpp

test.o: test.cpp test.h \
		UI/ui_test.h \
		login.h \
		viewbatch.h \
		qbatch.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

mainwds.o: mainwds.cpp mainwds.h \
		UI/ui_mainwds.h \
		mainwdsforonepage.h \
		mainwdsforfivepage.h \
		mainwdsforfourpage.h \
		mainwdsforthreepage.h \
		mainwdsfortwopage.h \
		iconhelper.h \
		myhelper.h \
		frmmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwds.o mainwds.cpp

mainwdsforonepage.o: mainwdsforonepage.cpp mainwdsforonepage.h \
		UI/ui_mainwdsforonepage.h \
		registrationinfo.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		changepasswd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwdsforonepage.o mainwdsforonepage.cpp

mainwdsfortwopage.o: mainwdsfortwopage.cpp mainwdsfortwopage.h \
		UI/ui_mainwdsfortwopage.h \
		setpermissions.h \
		changepermision.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		getlog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwdsfortwopage.o mainwdsfortwopage.cpp

mainwdsforthreepage.o: mainwdsforthreepage.cpp mainwdsforthreepage.h \
		UI/ui_mainwdsforthreepage.h \
		viewbatch.h \
		qbatch.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		userinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwdsforthreepage.o mainwdsforthreepage.cpp

mainwdsforfivepage.o: mainwdsforfivepage.cpp mainwdsforfivepage.h \
		UI/ui_mainwdsforfivepage.h \
		viewdata.h \
		filedata.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		qbatch.h \
		userinfo.h \
		maintaindata.h \
		saveproduct.h \
		session.h \
		viewdatathread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwdsforfivepage.o mainwdsforfivepage.cpp

mainwdsforfourpage.o: mainwdsforfourpage.cpp mainwdsforfourpage.h \
		UI/ui_mainwdsforfourpage.h \
		viewproline.h \
		setproline.h \
		modifyproline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwdsforfourpage.o mainwdsforfourpage.cpp

iconhelper.o: iconhelper.cpp iconhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconhelper.o iconhelper.cpp

frmmessagebox.o: frmmessagebox.cpp frmmessagebox.h \
		UI/ui_frmmessagebox.h \
		iconhelper.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmmessagebox.o frmmessagebox.cpp

frmmain.o: frmmain.cpp frmmain.h \
		UI/ui_frmmain.h \
		iconhelper.h \
		myhelper.h \
		frmmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmmain.o frmmain.cpp

mainwindowsforall.o: mainwindowsforall.cpp mainwindowsforall.h \
		UI/ui_mainwindowsforall.h \
		iconhelper.h \
		myhelper.h \
		frmmessagebox.h \
		mainwdsforonepage.h \
		mainwdsforfivepage.h \
		mainwdsforfourpage.h \
		mainwdsforthreepage.h \
		mainwdsfortwopage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindowsforall.o mainwindowsforall.cpp

work.o: work.cpp work.h \
		dbhelper.h \
		qres.h \
		qtray.h \
		product.h \
		quser.h \
		filedata.h \
		qbatch.h \
		userinfo.h \
		session.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o work.o work.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_rc.o: qrc_rc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rc.o qrc_rc.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_registered.o: moc_registered.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registered.o moc_registered.cpp

moc_getpasswd.o: moc_getpasswd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getpasswd.o moc_getpasswd.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_changepasswd.o: moc_changepasswd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changepasswd.o moc_changepasswd.cpp

moc_authentication.o: moc_authentication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_authentication.o moc_authentication.cpp

moc_registrationinfo.o: moc_registrationinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_registrationinfo.o moc_registrationinfo.cpp

moc_getlog.o: moc_getlog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getlog.o moc_getlog.cpp

moc_viewbatch.o: moc_viewbatch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewbatch.o moc_viewbatch.cpp

moc_setpermissions.o: moc_setpermissions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setpermissions.o moc_setpermissions.cpp

moc_viewproline.o: moc_viewproline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewproline.o moc_viewproline.cpp

moc_setproline.o: moc_setproline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setproline.o moc_setproline.cpp

moc_modifyproline.o: moc_modifyproline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifyproline.o moc_modifyproline.cpp

moc_saveproduct.o: moc_saveproduct.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_saveproduct.o moc_saveproduct.cpp

moc_maintaindata.o: moc_maintaindata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maintaindata.o moc_maintaindata.cpp

moc_viewdata.o: moc_viewdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewdata.o moc_viewdata.cpp

moc_addbatch.o: moc_addbatch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addbatch.o moc_addbatch.cpp

moc_qpnglineedit.o: moc_qpnglineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qpnglineedit.o moc_qpnglineedit.cpp

moc_changepermision.o: moc_changepermision.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changepermision.o moc_changepermision.cpp

moc_test.o: moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test.o moc_test.cpp

moc_mainwds.o: moc_mainwds.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwds.o moc_mainwds.cpp

moc_mainwdsforonepage.o: moc_mainwdsforonepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwdsforonepage.o moc_mainwdsforonepage.cpp

moc_mainwdsfortwopage.o: moc_mainwdsfortwopage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwdsfortwopage.o moc_mainwdsfortwopage.cpp

moc_mainwdsforthreepage.o: moc_mainwdsforthreepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwdsforthreepage.o moc_mainwdsforthreepage.cpp

moc_mainwdsforfivepage.o: moc_mainwdsforfivepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwdsforfivepage.o moc_mainwdsforfivepage.cpp

moc_mainwdsforfourpage.o: moc_mainwdsforfourpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwdsforfourpage.o moc_mainwdsforfourpage.cpp

moc_frmmessagebox.o: moc_frmmessagebox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmmessagebox.o moc_frmmessagebox.cpp

moc_frmmain.o: moc_frmmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmmain.o moc_frmmain.cpp

moc_mainwindowsforall.o: moc_mainwindowsforall.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindowsforall.o moc_mainwindowsforall.cpp

moc_work.o: moc_work.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_work.o moc_work.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

